FROM alpine

LABEL maintainer="mrlesmithjr@gmail.com"

RUN apk update && \
  apk add --no-cache bash openssh-client python3 py3-pip sshpass && \
  apk add --no-cache --virtual build-dependencies python3-dev libffi-dev \
  openssl-dev build-base && \
  pip3 install --upgrade pip &&\
  pip3 install --upgrade cffi && \
  pip3 install ansible && \
  if [ ! -e /usr/bin/pip ]; then ln -sf /usr/bin/pip3 /usr/bin/pip; fi && \
  if [ ! -e /usr/bin/python ]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
  apk del --purge build-dependencies && \
  rm -rf /var/cache/apk/* /tmp/*