FROM alpine

LABEL maintainer="mrlesmithjr@gmail.com"

RUN apk update && \
  apk add --no-cache --virtual build-dependencies python-dev libffi-dev \
  openssl-dev build-base py-pip && pip install -U cffi && pip install ansible

